<?php
// Plugin definition
$plugin = array(
  'title' => t('trainingcourseview'),
  'icon' => 'trainingcourseview.png',
  'category' => t('Responsive'),
  'theme' => 'trainingcourseview',
  'css' => 'trainingcourseview.css',
  'regions' => array(
    'column1' => t('First Column'),
    'column2' => t('Second Column'),
    'column3' => t('Third Column'),
	
	'column4' => t('Fourth Column'),
    'column5' => t('Fifth Column'),
    'column6' => t('Sixth Column'),
	
	'column7' => t('Seventh Column'),
	
  ),
);
